version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      codeql:
        patterns:
          - "github/codeql-action*"

  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
      - npm
    schedule:
      interval: daily
    groups:
      eslint:
        patterns:
          - "*eslint*"
