name: Lint Code Base

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Lint Code Base
        id: super-linter
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_JSCPD: false
          GITLEAKS_CONFIG_FILE: .gitleaks.toml
          FILTER_REGEX_EXCLUDE: "(CHANGELOG|CODE_OF_CONDUCT|CONTRIBUTING|SECURITY|SUPPORT)\\.md$|(^|.*/)dist/"
